set pastetoggle=<F2>
set number
set mouse=a
set t_ut=
syntax enable

execute pathogen#infect()
syntax on
filetype plugin indent on

colorscheme industry 

set nocompatible
set hlsearch
set incsearch
set expandtab
set shiftwidth=4
set tabstop=4
set showcmd
set autoindent
set ignorecase
set smartcase
set backspace=indent,eol,start
set ttimeoutlen=10

nnoremap <leader>r :!%:p<Enter>

