set pastetoggle=<F2>
set number
set mouse=a
set termguicolors
syntax enable

execute pathogen#infect()
syntax on
filetype plugin indent on

colorscheme wonka-dark 

set nocompatible
set hlsearch
set incsearch
set expandtab
set shiftwidth=4
set tabstop=4
set showcmd
set autoindent
set ignorecase
set smartcase
set backspace=indent,eol,start
set ttimeoutlen=10

nnoremap <leader>r :w<Enter>:!%:p<Enter>
nnoremap <leader>t :w<Enter>:!fish<Enter>
nnoremap <leader>w :w<Enter>
nnoremap <leader>n :noh<Enter>
nnoremap <leader>s :%s/

let g:airline_powerline_fonts = 1
let g:airline_theme='base16_embers'

" Force tmux to use tmuxline colors from start
let g:airline#extensions#tmuxline#enabled = 1
let airline#extensions#tmuxline#snapshot_file = "~/.tmux-status.conf"

