set pastetoggle=<F2>
set number
set mouse=a
set t_ut=
syntax enable

execute pathogen#infect()
syntax on
filetype plugin indent on

colorscheme industry 

set nocompatible
set hlsearch
set incsearch
set expandtab
set shiftwidth=4
set tabstop=4
set showcmd
set autoindent
set ignorecase
set smartcase
set backspace=indent,eol,start
set ttimeoutlen=10

nnoremap <leader>r :w<Enter>:!%:p<Enter>
nnoremap <leader>t :w<Enter>:sh<Enter>
nnoremap <leader>w :w<Enter>
nnoremap <leader>n :noh<Enter>
nnoremap <leader>s :%s/
nnoremap <leader>F ][zf%
nnoremap <leader>f za
nnoremap <leader>c :so ~/.vimrc

